# Generated by Django 5.1.7 on 2025-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
