# Generated by Django 5.1.7 on 2025-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0002_evstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='evstation',
            name='gps_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
