# Generated by Django 4.2.20 on 2025-04-05 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0004_station_userprofile_userpreferences_chargingsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charger',
        ),
        migrations.DeleteModel(
            name='EvStation',
        ),
    ]
