# Generated by Django 4.2.20 on 2025-05-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0005_delete_charger_delete_evstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domestic_tariff', models.DecimalField(decimal_places=2, max_digits=10)),
                ('public_charging_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('average_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('battery_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
