# Generated by Django 5.2 on 2025-05-15 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ev', '0002_calculator_seed_data'),
        ('ev', '0006_state_vehiclesegment'),
    ]

    operations = [
    ]
